name: 'Build library and run tests'

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-22.04
    steps:
    - uses: actions/checkout@v2
    - name: Apt update
      run: sudo apt update
    - name: Install depends
      run: sudo apt install meson libwayland-dev libgtk-3-dev gobject-introspection libgirepository1.0-dev valac gtk-doc-tools
    - name: Meson
      run: meson build -Dexamples=true -Ddocs=true -Dtests=true
      env:
        CFLAGS: -Werror
    - name: Build
      run: ninja -C build
    - name: Test
      run: ninja -C build test
    - name: Install
      run: sudo ninja -C build install
    - name: Meson Vala example
      run: cd examples/vala-standalone && meson ../../vala-build
    - name: Build Vala example
      run: ninja -C vala-build
